bootcfg: Do not fail on missing BootCurrent entry
EfiBootConfig.parse_boot_variables() adds BootCurrent to 'bentr' list but
the corresponding BootXXXX entry is not guaranteed to be present. In case
it's missing, 'kernel-bootcfg --add-uki/--remove-uki' fail miserably:

Traceback (most recent call last):
  File "/usr/local/bin/kernel-bootcfg", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/virt/firmware/bootcfg/main.py", line 242, in main
    add_uki(cfg, options)
  File "/usr/local/lib/python3.12/site-packages/virt/firmware/bootcfg/main.py", line 40, in add_uki
    nr = cfg.find_uki_entry(efiuki.efi_filename())
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/virt/firmware/bootcfg/bootcfg.py", line 96, in find_uki_entry
    if not entry.optdata:
           ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'optdata'

Skip missing entries in find_uki_entry() to avoid the problem, we have no
interest in such entries anyway.

Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>